matrix:
  include:
    - language: csharp
      script:
        - cd CSharp && mcs Example.cs MineStat/MineStat.cs

    - language: go
      #go_import_path: github.com/FragLand/minestat
      install:
        - echo "Skipping default install process..."
      script:
        - cd Go && go build example.go

    - language: java
      jdk: openjdk9
      script:
        - cd Java && javac Example.java

    - language: ruby
      script:
        - cd Ruby && gem build minestat.gemspec && gem install minestat
